- name: practising variables and defining variables
  hosts: local
  connection: local
  become: yes
  vars:
    course: "DevOps with AWS"
    Trainer: "siva"
    Hours: "140+"
  tasks:
  - name: printing the course details
    ansible.builtin.debug:
      msg: Hi iam learning {{ course }} and is {{ Trainer }} and {{ Hours}}