- name: task level variables
  hosts: local
  connection: local
  vars_files:
   - vars.yml
  tasks:
  - name: variables on task level
    vars:
      COURSE: "Ansible"
      Trainer: "Siva"
    ansible.builtin.debug:
      msg: currently im learning {{ COURSE }} and my trainer is {{ Trainer }} and duration is {{ Duration }}