- name: practising prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: please enter your username
    private: false
  - name: password
    prompt: please enter your password
    private: true
  tasks:
  - name: printing from prompts
    ansible.builtin.debug:
     msg: "printing {{ username }} and user password {{ password }}"