- name: installing nginx server and starting it and taking the output through prompt
  hosts: web
  become: yes
  vars_prompt:
  - name: app
    prompt: please enter application name
    private: false
  tasks:
    - name: installing application
      ansible.builtin.package:
        name: "{{ app }}"
        state: present

    - name: printing the message
      ansible.builtin.debug:
        msg: "{{ app }} successfully installed"

