- name: practising conditions in ansible
  hosts: local
  connection: local
  become: yes
  vars_prompt:
  - name: choice
    prompt: enter the number
    private: false
  tasks:
  - name: checking the value
    ansible.builtin.package:
     name: nginx
     state: present
    when: choice == "1"
  - name:  if the number is 2 then install httpd
    ansible.builtin.package:
     name: httpd
     state: present
    when: choice == "2"
  
