- name: practising conditions in ansible
  hosts: local
  connection: local
  become: yes
  vars_prompt:
  - name: choice
    prompt: enter the number
    private: false
  tasks:
  - name: as you have entered 1 nginx will be installed
    ansible.builtin.package:
     name: nginx
     state: present
    when: choice == "1"
  - name:  as you have entered 2 httpd will be installed
    ansible.builtin.package:
     name: httpd
     state: present
    when: choice == "2"
  - name: printing the values
    ansible.builtin.debug:
      msg: "request completed based on your input"
  
